name: Deploy Master and Patch to GitHub Pages
on:
  push:
    branches:
      - master
      - steveseguin-patch-1
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create deployment structure
        run: mkdir -p gh-pages-content/patch
          
      - name: Checkout master branch
        uses: actions/checkout@v4
        with:
          ref: master
          path: master-content
          
      - name: Checkout patch branch
        uses: actions/checkout@v4
        with:
          ref: steveseguin-patch-1
          path: patch-content
          
      - name: Prepare content
        run: |
          # Copy master content to deployment root
          cp -r master-content/* gh-pages-content/ || true
          cp -r master-content/.* gh-pages-content/ 2>/dev/null || true
          
          # Copy patch content to patch directory
          cp -r patch-content/* gh-pages-content/patch/ || true
          cp -r patch-content/.* gh-pages-content/patch/ 2>/dev/null || true
          
          # Debug: list content
          echo "Deployment content:"
          ls -la gh-pages-content
          echo "Patch content:"
          ls -la gh-pages-content/patch

      - name: Setup Pages
        uses: actions/configure-pages@v3
        
      - name: Push to gh-pages branch
        run: |
          cd gh-pages-content
          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy to GitHub Pages"
          git branch -M gh-pages
          git remote add origin https://${{ github.actor }}:${{ github.token }}@github.com/${{ github.repository }}.git
          git push -f origin gh-pages
