name: Deploy Master and Patch to GitHub Pages
on:
  push:
    branches:
      - master
      - steveseguin-patch-1
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create deployment structure
        run: |
          # Create base directory for deployment
          mkdir -p deployment
          mkdir -p deployment/patch
          
      - name: Checkout master branch
        uses: actions/checkout@v4
        with:
          ref: master
          path: master-content
          
      - name: Checkout patch branch
        uses: actions/checkout@v4
        with:
          ref: steveseguin-patch-1
          path: patch-content
          
      - name: Prepare content
        run: |
          # Copy master content to deployment root
          cp -r master-content/* deployment/ || true
          cp -r master-content/.* deployment/ 2>/dev/null || true
          
          # Copy patch content to patch directory
          cp -r patch-content/* deployment/patch/ || true
          cp -r patch-content/.* deployment/patch/ 2>/dev/null || true
          
          # Debug: list content
          echo "Deployment content:"
          ls -la deployment
          echo "Patch content:"
          ls -la deployment/patch

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: deployment
          branch: gh-pages
