name: Deploy Master and Patch to GitHub Pages
on:
  push:
    branches:
      - master
      - steveseguin-patch-1
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v4
        with:
          ref: master
          path: deploy-content

      - name: Create patch directory
        run: mkdir -p deploy-content/patch

      - name: Checkout patch branch
        uses: actions/checkout@v4
        with:
          ref: steveseguin-patch-1
          path: patch-content

      - name: Copy patch content
        run: cp -r patch-content/* deploy-content/patch/

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: deploy-content
          branch: gh-pages
          clean: true
