name: Deploy Master and Patch to GitHub Pages
on:
  push:
    branches:
      - master
      - steveseguin-patch-1
  workflow_dispatch:
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch content
        uses: actions/checkout@v4
        with:
          ref: master
          path: public
          
      - name: Configure Git
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE/public"
          
      - name: Checkout patch branch content into patch subfolder
        uses: actions/checkout@v4
        with:
          ref: steveseguin-patch-1
          path: public/patch
          
      - name: Configure Git for patch directory
        run: |
          git config --global --add safe.directory "$GITHUB_WORKSPACE/public/patch"
          
      - name: Deploy to gh-pages branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: public
          clean: true
