name: Deploy Master and Patch to GitHub Pages
on:
  push:
    branches:
      - master
      - steveseguin-patch-1
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up directory structure
        run: |
          # Create the deployment directory structure
          mkdir -p deploy/patch
          
          # Get the master branch content
          git fetch origin master:master
          git archive master | tar -x -C deploy
          
          # Get the patch branch content
          git fetch origin steveseguin-patch-1:steveseguin-patch-1
          git archive steveseguin-patch-1 | tar -x -C deploy/patch
          
          # List the files to verify
          echo "Content structure:"
          ls -la deploy
          echo "Patch content:"
          ls -la deploy/patch

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: deploy
          branch: gh-pages
