name: Build Electron App for Linux

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    env:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build Electron app for Linux
        run: npm run build:linux
        
      - name: Archive Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: electron-linux-AppImage
          path: dist/*.AppImage
          retention-days: 1
        
      - name: Build Electron deb for RPI
        run: npm run build:rpideb
        
      - name: Archive Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: electron-rpi-deb
          path: dist/*.deb
          retention-days: 1
        
      - name: Build Electron appImage for RPI
        run: npm run build:rpi

      - name: Archive Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: electron-rpi-AppImage
          path: dist/*.AppImage
          retention-days: 1




